# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.2.0', '< 4.0'

gem 'dotenv', '~> 2.8'
gem 'faraday', '~> 2.0'
gem 'json', '~> 2.6'
gem 'logger', '~> 1.5'
gem 'oj', '~> 3.15' # Fast JSON parsing
gem 'puma', '~> 7.1'
gem 'rack-protection', '~> 3.0'
gem 'rack-timeout', '~> 0.6'
gem 'redis', '~> 5.0'
gem 'sinatra', '~> 3.0'
gem 'thor', '~> 1.3' # CLI framework (Shopify CLI style)

group :development, :test do
  gem 'pry', '~> 0.14'
  gem 'rspec', '~> 3.12'
  gem 'rubocop', '~> 1.57'
end
