AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/examples.txt'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes
